baseURL: "https://www.hadithtech.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Hadith Tech"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Hadith Tech podcast"
  description: "Awesome fireside tech interviews with technology leaders!"
  images: 
    - "images/hero-image.png"

  # logo: "arrow-up.png"

  # favicons:
  #   themeColor: "#000000"
  #   backgroundColor: "#000000"
  #   faviconColor: "#000000"

  social:
    # dribbble: "#"
    instagram: "https://www.instagram.com/hadith_tech/"
    facebook: "https://www.facebook.com/hadithtech"
    twitter: "https://twitter.com/hadith_tech"

  location:
    - "in the <3 of community"
  #   - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "DM us on twitter"
    # - "207.555.0119"

  # copyright: "© 2022 Up Business All Rights Reserved"

menus:
  # main:
  #   - name: "Home"
  #     url: "/#hero"
  #     weight: 1

  #   - name: "How we work"
  #     url: "/#"
  #     weight: 2

  #   - name: "Our team"
  #     url: "/#"
  #     weight: 3

  #   - name: "Pricing"
  #     url: "/#"
  #     weight: 4

  #   - name: "Blog"
  #     url: "/blog"
  #     weight: 5

  # buttons:
  #   - name: "Book a call"
  #     url: "/#"
  #     weight: 5
  #     pre: "btn btn-primary text-light"

  footer:
    - name: "Host"
      url: "https://www.abdurrahmanrajab.com/"
      weight: 1

  #   - name: "How we work"
  #     url: "/#"
  #     weight: 2

  #   - name: "Our team"
  #     url: "/#"
  #     weight: 3

  #   - name: "Pricing"
  #     url: "/#"
  #     weight: 4

  #   - name: "Blog"
  #     url: "/blog"
  #     weight: 5

taxonomies:
  series: "series"
  tags: "tags"
